services:
  - docker

language: c

env:
  # Use the last stable release to run more tests
  - tag=pg12-geos37-gdal30-proj611 mode=tests
  - tag=pg12-geos37-gdal30-proj611 mode=debug
  - tag=pg12-geos37-gdal30-proj611 mode=coverage
  - tag=pg12-geos37-gdal30-proj611 mode=usan_gcc
  - tag=pg12-clang-geos37-gdal30-proj611 mode=usan_clang
  - tag=pg12-geos37-gdal30-proj611 mode=nowagyu

  # Run tests with different dependecy combinations
  - tag=latest mode=tests
  - tag=pg11-geos37-gdal24-proj52 mode=tests
  - tag=pg10-geos36-gdal23-proj49 mode=tests
  - tag=pg96-geos36-gdal22-proj49 mode=tests
  - tag=pg95-geos36-gdal21-proj48 mode=tests

matrix:
  allow_failures:
    - env: tag=latest mode=tests

script:
  - echo "/tmp/logbt-coredumps/core.%p.%E" | sudo tee /proc/sys/kernel/core_pattern
  - echo "FROM postgis/postgis-build-env:${tag}" > Dockerfile
  - echo "ADD --chown=postgres:postgres . /src/postgis" >> Dockerfile
  - echo "CMD bash ci/travis/run_${mode}.sh" >> Dockerfile
  - docker build -t pgtest .
  - ci_env=`bash .github/codecov_env.bash`
  - docker run $ci_env --name pgtest-${TRAVIS_BUILD_NUMBER} pgtest

after_success:
  - docker rm pgtest-${TRAVIS_BUILD_NUMBER}

notifications:
  email: false
